---
title: "La Polis: Una introducción a la antigua ciudad-estado griega (Herman Hansen De Mogen)."
date: "2024-07-12"
cover:
  image: "Hefestión.webp"
  # can also paste direct link from external site
  # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
  alt: "El Hefestión visto desde el ágora en Atenas, Grecia. Foto de Eduardo Alemán."
  caption: "El Hefestión visto desde el ágora en Atenas, Grecia. Foto de Eduardo Alemán."
  relative: false # To use relative path for cover image, used in hugo Page-bundles
categories: 
  - "antigüedad"
  - "grecia"
  - "polis"
  - "ciudad-estado"
  - "cultura de ciudad-estado"
  - "herman hansen de mogen"
  - "traducción"
---

Hansen, Mogens Herman, [_Polis: An Introduction to the Ancient Greek City-State_](https://amzn.to/3zHpZqA), 2006, Introducción, Capítulo 1. Traducción en español de Eduardo Alemán.

## Para John Crook

Este libro es una versión ampliada y revisada de mi libro en danés: _Polis: den oldgræsk bystatskultur_ (Copenhague, 2004). Cuando se publicó, envié copias a colegas y amigos, incluido, por supuesto, John Crook. Le gustó y se ofreció a producir una versión en inglés. Ofrecida la oportunidad, acepté la propuesta con gratitud; recuerdo los momentos felices que pasamos juntos en el invierno y la primavera de 1990 trabajando en la traducción de _La democracia ateniense en la época de Demóstenes_. Tuvimos una repetición de eso en agosto de 2002 al traducir mi ensayo sobre _The Triumph of Time: Reflections of a Historian about Time in History_. Esta primavera lo hicimos por tercera vez y aquí está el resultado. Permítanme aprovechar esta oportunidad para agradecer a John Crook por su amistad y todo lo que he aprendido de él durante más de treinta años y, por supuesto, por los agradables días que pasamos juntos en Cambridge trabajando en la traducción y transmitiéndola a mi fiel seguidor: Ollie el segundo.

## Introducción

Polis es la palabra griega antigua que significa "ciudad",1 "estado"2 y la combinación de ciudad y estado, la "ciudad-estado".3 A menudo, y con razón, se ha dicho que la polis, como forma de estado, y de la sociedad, fue la base de toda la civilización griega; y la implicación de esto es que uno sólo puede entender la civilización griega si comprende la forma de la sociedad bajo la cual vivían los griegos, es decir, la polis. Sin embargo, lamentablemente esta esclarecedora verdad rara vez va seguida de una descripción de lo que realmente es una polis (o más bien lo que era, pues la forma de cultura de ciudad-estado que dominó Grecia en la antigüedad ya no existe en ninguna parte del mundo). Nos han faltado estudios exhaustivos y fundamentales de la polis como concepto y como fenómeno real: las investigaciones anteriores han sido subjetivas y los ejemplos elegidos se tomaron en su mayoría de fuentes que trataban de Atenas. Pero Atenas era sólo una entre unas 1.500 poleis y era anómala en muchos aspectos. ¿Y qué pasa con las aproximadamente 1.499 otras poleis? Se ha escrito muy poco sobre ellas,4 y esa es una de las razones por las que sigue habiendo profundo desacuerdo sobre casi todas las preguntas fundamentales que pueden plantearse sobre la polis: cuándo surgió, cuándo llegó a su fin, cuántas poleis había y exactamente dónde estaban situadas, fueron una fusión de Estado y sociedad o, por el contrario, una sociedad pero no un Estado, es decir, sin las instituciones que caracterizan un estado. También hay desacuerdo sobre hasta qué punto una polis era una sociedad de ciudadanos varones adultos o si incluía mujeres, niños, forasteros, esclavos, etc. Todos estos problemas no resueltos (y a menudo no abordados) fueron el trasfondo que llevó a la creación por parte de la Fundación Nacional Danesa de Investigación en 1993 de una centro para el estudio de la antigua ciudad-estado griega: el Centro Polis. Fue en la Universidad de Copenhague, en la Facultad de Humanidades, y su cometido principal era describir la forma de Estado y asentamiento típico de la antigua Grecia, la polis, la ciudad-estado. A partir de un gran número de investigaciones publicadas sobre la polis, tanto como forma de Estado como de asentamiento, ha sido posible por primera vez crear un Inventario de todas las poleis griegas conocidas en los períodos Arcaico y Clásico (_c_.650 a 323 a. C.); y a partir de ese Inventario hemos realizado un análisis de la polis-mundo griega antigua. Esto ha producido una nueva evaluación y una revisión de muchas doctrinas estándar sobre el desarrollo y el carácter de la polis griega. El Inventario fue publicado por Oxford University Press en 2004.5

La segunda tarea del Centro fue comprender la polis en un contexto histórico mundial más amplio. La antigua polis griega era una ciudad-estado, y cuando los historiadores hoy en día hablan de ciudades-estado, piensan ante todo en la antigua Grecia y después en las ciudades del norte de Italia en la Edad Media. Pero ha habido ciudades-estado en otros lugares y en otras épocas. Un análisis general de la urbanización y la formación de estados muestra que en la historia mundial desde la antigüedad hasta _c._ 1900 han existido dos tipos diferentes de estados: macroestados, con numerosas ciudades incluidas en el territorio de cada uno de ellos, frente a regiones divididas en microestados, cada uno de los cuales constaba de una ciudad y su interior. Un microestado de este tipo es lo que se llama una “ciudad-estado”, y las regiones divididas en ciudades-estado forman lo que el Centro Polis ha llamado una “cultura de ciudad-estado”. Hemos logrado identificar treinta y siete "culturas de ciudades-estado", desde los sumerios en Mesopotamia en el tercer milenio a. C. hasta varias culturas de ciudades-estado en África occidental que fueron aniquiladas por las potencias coloniales hace poco más de cien años.6 Tampoco en este asunto nadie ha intentado todavía obtener una imagen general de cuántas y qué tipo de culturas de ciudades-estado ha habido en la historia del mundo.

Para resumir los resultados de las investigaciones del Centro Polis, destaco cuatro características. En las culturas de las ciudades-estado, incluida la de la antigua Grecia, ha habido (1) un grado de urbanización sin precedentes en los principales estados antes de la Revolución Industrial, que comenzó en la segunda mitad del siglo XVIII; (2) una economía basada en el comercio y centrada en el mercado de la ciudad; (3) un proceso de toma de decisiones políticas mediante el cual las leyes y decretos no siempre eran dictados por un monarca, sino que a menudo eran aprobados por mayoría de votos después de un debate en una asamblea, que en su mayoría era una selección entre los ciudadanos de mejor clase, pero que a veces incluía a todos los ciudadanos; (4) interacción entre ciudades-estado, que resultó en el surgimiento de ligas de estados y estados federales. Como tipo de estado, el estado federal creció dentro de las culturas de las ciudades-estado y sólo apareció como un macroestado con la fundación de los Estados Unidos en 1787-1789.

Ya no queda ninguna cultura de ciudad-estado; la última de ellas desapareció en _c._ 1900. Por eso es una ironía de la historia que la organización social, económica y política que caracterizaba las culturas de las ciudades-estado no desapareció cuando estas desaparecieron, sino que llegó a dominar los estados y las sociedades en el mundo que tenemos hoy. En muchos aspectos importantes, los macroestados modernos se parecen más a las antiguas culturas de ciudades-estado que a los antiguos macroestados.

Esta breve reseña está diseñada para un amplio grupo de lectores interesados ​​y también para el público más reducido de eruditos clásicos, arqueólogos, antropólogos, sociólogos e historiadores, que en el curso de su trabajo profesional tienen que llegar a un acuerdo con lo que se entiende por una ciudad, un estado y una ciudad-estado. El presente libro consta de tres partes. La primera es una visión relativamente amplia de los conceptos de ciudad-estado y cultura de ciudad-estado y de las treinta y siete culturas de este tipo que creemos haber descubierto en la historia de la humanidad. La segunda es una descripción específica de la antigua polis griega, y la tercera es una conclusión, en la que se compara la polis griega con las otras treinta y seis culturas de ciudades-estado y con el concepto de cultura de ciudad-estado como tal.

### Notas de la Introducción

1.  Defino una ciudad estructuralmente como un área densamente urbanizada asentada con, al menos, un número de habitantes de cuatro dígitos (_infra_ cap. 9 n. 6) y funcionalmente como un lugar central que realiza una serie de tareas especializadas en relación con el interior (_infra_ cap. 14 n. 12). Políticamente, los habitantes están organizados a veces como un municipio, a veces como una entidad política (polis). Como la mayoría de los antropólogos, arqueólogos e historiadores, uso los términos "pueblo" y "ciudad" para referirme al mismo asentamiento nucleado (_30 CSC_: 25), pero en contextos diferentes: cuando un centro urbano es visto como un conjunto de casas, tiendo a llamarlo pueblo; cuando el énfasis está en los habitantes y su organización social y política, le llamo ciudad. Esta distinción coincide con la distinción en francés entre _ville_ y _cité_. Cf. Rousseau, _Du contrat social_, la nota de la pág. 361 en la Pléiade edn.: “Le vrai sens de ce mot c’est presque entièrement effacé chez les modernes; la plupart prennent une ville pour une Cité et un bourgeois pour un Citoyen. Ils ne savent pas que les maisons font la ville mais que les Citoyens font la cité.” Para _Polis_ como tipo de ciudad, véase 62. A los asentamientos nucleados más pequeños los llamo aldeas, véase _infra_ 68–9. 
    
2.  Defino un estado como un territorio determinado, una población determinado y un gobierno central institucionalizado con el derecho exclusivo de establecer y hacer cumplir un orden legal dentro del territorio sobre la población; ver _infra_ 7 con n. 3, 63–5 y Hansen (1998) 114–23.
    
3.  El término inglés "ciudad-estado" probablemente fue acuñado en 1885 como una traducción del término alemán _Stadtstaat_ en relación con la traducción al inglés de J. Bluntschli, _Allgemeine Staatslehre_, 6ª ed. (Berlín, 1886), 63 = _Theory of the State_ (Londres, 1885), 60. El término alemán _Stadtstaat_ probablemente fue acuñado en 1842 como una traducción del término danés _Bysta_t (_by_ = ciudad; cf. Derby) en relación con la traducción al alemán de J. N. Madvig, _Blik på Oldtidens Statsforfatninger med Hensyn til Udviklingen af Monarkiet og en omfattende Statsorganisme_ (Copenhague, 1840) = _Blicke auf die Staatsverfassung des Altertums, mit Rücksicht auf die Entwicklung der Monarchie und eines umfassenden Staatsorganismus_, in _Archiv für Geschichte, Statistik, Kunde der Verwaltung und Landesrechte der Herzogthümer Schleswig_, Holstein y Lauenburg (Kiel, 1842), 42. El término francés _cité-État_ y el término italiano _cittá-stato_ ambos se derivan de _Stadtstaat_ y/o _city-state_, y ninguno de los dos está atestiguado antes del siglo XX (Hansen (1998) 15-16). Los términos _Bystat_ y _Stadtstaat_ se aplicaron por primera vez a Roma en el período republicano, y sólo más tarde se transfirieron a descripciones, principalmente, de la antigua _polis_ griega y de la _città_ en la Italia medieval. Fue sólo a partir de 1950, como consecuencia de la nueva comprensión del urbanismo como un fenómeno global, que los conceptos de ciudad-estado, _Stadtstaat_, etc. se han extendido a las civilizaciones mesoamericana, africana y asiática (_30 CSC_: 604 con nn. 32-4).
    
4.  Cuatro excepciones recomendables son la investigación de Ruschenbusch sobre el número de _poleis_ (1985), _Jenseits von Athen und Sparta_ de Gehrke (1986), _Cités et royaumes du monde grec: espace et politique_ de Bertrand (1992) y el libro de Brock y Hodkinson (eds.), _Alternatives to Athens_ (2000).
    
5.  Las investigaciones realizadas por el Centro Polis de Copenhague se han publicado en dos series: (1) _Acts of the Copenhagen Polis Centre = CPCActs_ 1–7 (contribuciones a los siete simposios internacionales que organizó el Centro; la serie Actas es publicada por la Real Academia Danesa); y 2) _Papers from the Copenhagen Polis Centre = CPCPapers_ 1–7 (artículos escritos por académicos que han colaborado con el Centro; la serie Papers es publicada por Steiner Verlag como _Historia_, Einzelschriften 87, 95, 108, 117, 138, 162, 180). Para obtener una lista completa de las publicaciones del Centro Polis, consulte _infra_ 191–3.
    
6.  Publicado en _A Comparative Study of Thirty City-State Cultures (=30 CSC)_ y _A Comparative Study of Six City-State Cultures (= 6 CSC)_.
    

## Capítulo 1: Ciudades, Estados, Ciudades-Estado y Culturas de Ciudades-Estado

A muy largo plazo, hay tres hitos en la historia de la humanidad antes de la Revolución Industrial: (1) el cambio de la caza y la pesca a la agricultura y el pastoreo como modo más importante de ganarse la vida, (2) el cambio de la actividad dispersa a la asentamiento nucleado, primero en aldeas y luego en verdaderas ciudades, (3) el cambio en la estructura social de grupos más flexibles de base familiar a comunidades institucionalizadas con primero la tribu y luego el Estado como unidad política dominante.1

(1) En nuestra parte del mundo, la “revolución agraria” comenzó hacia el año 8000 a. C., es decir, en el período Neolítico y en el Cercano Oriente entre Asia Menor y Mesopotamia.

(2) A la “revolución agraria” le siguió rápidamente el asentamiento en aldeas permanentes: las primeras ciudades surgieron ya en la Edad de Piedra. Una de las más antiguas es Çatal Höyük en Turquía, a unos 250 km al sur de Ankara, una ciudad de la Edad de Piedra de 16 hectáreas, llena de casas unidas de pared a pared sin calles de por medio. Floreció en el período 6800-6300 a. C. y llegó a tener unos 5.000 habitantes.2

(3) La forma muy unida de asentamiento en aldeas y ciudades dio lugar a la necesidad de regular el comportamiento social de la gente. Las primeras sociedades tribales estaban típicamente gobernadas por asambleas de todos los miembros de la tribu, por consejos de los ancianos del grupo y, en algunos casos, por jefes. Sólo más tarde vino la fundación de estados reales, es decir, la creación de un liderazgo político institucionalizado y centralizado con un monopolio legítimo de la fuerza para establecer y mantener un orden legal dentro de un territorio determinado y sobre una población determinada.3

La “revolución agraria” y el asentamiento en pueblos y ciudades se pueden observar en los vestigios encontrados por los arqueólogos: polen y huesos de animales, restos de edificios y objetos domésticos. Es más difícil encontrar rastros arqueológicos de estructuras sociales humanas y formas de organización política. Así, por lo general, sólo tendremos un conocimiento seguro del crecimiento real de los estados cuando alcancen el conocimiento de la escritura. En nuestra parte del mundo, las dos civilizaciones más antiguas donde podemos encontrar pruebas irrefutables del surgimiento de estados son Mesopotamia y Egipto, donde documentos en escritura cuneiforme (de aproximadamente 3200 a. C.) y jeroglíficos (de aproximadamente 3000 a. C.) nos brindan una información detallada de la forma de esas sociedades. No se puede excluir que Çatal Höyük en la Edad de Piedra pudiera haber tenido una organización política como algún tipo de estado: no lo sabemos y tal vez nunca lo sabremos.4

Entonces, dicho en términos muy generales, el patrón de desarrollo en la historia mundial ha sido que la agricultura condujo a asentamientos fijos y a una densidad de población que, a su vez, creó la posibilidad de la urbanización y el surgimiento de estados. Pero ¿cuál es la relación entre agricultura y urbanización y la creación de estados? ¿Los tres están indisolublemente unidos, o podemos encontrar sociedades sin crecimiento de ciudades y estados, o estados sin ciudades, o ciudades sin estados?

Hay muchos ejemplos de civilizaciones sin agricultura, urbanización o formación de estados (por ejemplo, las tribus indias norteamericanas y numerosas sociedades nómadas). También se pueden encontrar ejemplos de estados sin ciudades (por ejemplo, los siete estados anglosajones en Inglaterra entre 500 y 700 d. C.)5 y de sociedades con ciudades pero sin estado (por ejemplo, el pueblo Yakö en Nigeria hasta principios del siglo XX)6. Sin embargo, al mismo tiempo podemos decir con certeza que en el mayor número de civilizaciones sobre las que leemos en la historia mundial, los pueblos estaban asentados permanentemente y organizados en estados: en su mayoría eran agricultores que vivían dispersos o en aldeas, pero algunos de ellos ellos en verdaderas ciudades.

La urbanización está estrechamente relacionada con el crecimiento de los estados, por lo que los dos procesos a menudo ocurren en un período de tiempo que indica la estrecha relación de los fenómenos. Si bien a una sociedad agrícola a menudo le toma miles de años embarcarse en la formación del Estado y la urbanización, rara vez transcurre mucho tiempo entre la formación de los Estados y la formación de las ciudades, tal vez como máximo unos pocos cientos de años; y normalmente los dos fenómenos son simultáneos y sin duda cada uno influye sobre el otro. En Dinamarca, la agricultura y el pastoreo se remontan aproximadamente al 4000 a.C. Pasaron unos 5.000 años antes de que Dinamarca se convirtiera en un estado en la época vikinga, como se muestra _inter alia_ por la piedra de Jelling en la que Harald Bluetooth declaró que “conquistó para sí toda Dinamarca y Noruega e hizo cristianos a los daneses”. Y al mismo tiempo podemos observar el crecimiento de las ciudades: primero Hedeby y Ribe, y después Ålborg, Århus y Odense, impulsado por el nuevo poder real.7

Así pues, la formación de ciudades y la formación de Estados van de la mano; pero las relaciones entre ellos varían. A menudo, la formación de estados cubre áreas muy grandes, con varias ciudades en el territorio de cada estado: ejemplos son Egipto en la antigüedad, Dinamarca en la época vikinga y el Imperio Inca a finales de la Edad Media. Sin embargo, hay una serie de ejemplos en los que existe una especie de relación una a una entre la formación de una ciudad y la formación de un estado, en los que cada ciudad es el centro de un pequeño estado que consta de una ciudad más un interior y, visto desde el lado opuesto, cada estado es relativamente pequeño y, por lo general, tiene una sola ciudad como centro de la sociedad. Y eso es lo que llamamos ciudad-estado. Los ejemplos más antiguos conocidos son las ciudades-estado sumerias en Mesopotamia desde _c._ 3100 a. C., siendo Uruk la más grande entre unas cincuenta otras. Pero ha habido muchas otras ciudades-estado en la historia mundial: Atenas fue una en la antigüedad, Venecia lo fue hasta 1797, Bremen de 1741 a 1937. Danzig fue todavía una ciudad-estado entre las guerras mundiales, 1919-1939, y hasta el día de hoy Andorra en los Pirineos es una.

Sin embargo, no es satisfactorio poner todas estas ciudades-estado bajo un mismo sombrero. Uruk, Atenas y Venecia eran ciudades-estado situadas entre otras ciudades-estado. Bremen, Danzig y Andorra eran ciudades-estado aisladas. Bremen estaba entre Oldenburg y Hannover, Danzig estaba rodeada entre Alemania y Polonia, y Andorra se encontraba entre España y Francia. Por lo tanto, debemos distinguir entre una ciudad-estado y un grupo de ciudades-estado, lo que, en la terminología de nuestro proyecto, se denomina “cultura de ciudad-estado”. Distinguir el concepto de "cultura de ciudad-estado" del de "ciudad-estado" es uno de los objetivos centrales de la investigación del Centro Polis, y definimos una cultura de ciudad-estado de la siguiente manera: una cultura de ciudad-estado surge cuando una región está habitada por un pueblo que tiene la misma lengua (o una común _lingua franca_), la misma religión, la misma cultura y las mismas tradiciones, pero está dividida políticamente en un gran número de pequeños estados, cada uno de los cuales consta de una ciudad y su interior inmediato.8

Una cultura de ciudad-estado surge típicamente de una de tres maneras. (a) Después de un período sin formación de estados, ocurre un período de crecimiento económico y poblacional, en el que todo el territorio está urbanizado y organizado políticamente como un conjunto de ciudades-estado. Esto es lo que ocurrió, por ejemplo, en las antiguas ciudades-estado griegas en el siglo VIII a.C. (b) Un estado más grande con muchas ciudades se divide y cada ciudad se convierte en una unidad autónoma. Así es como surgieron las ciudades-estado chinas en el período de primavera y otoño, 771-481 a.C. (c) Un pueblo inmigrante se instala en ciudades-estado, o las ciudades-estado surgen poco después de la colonización. Eso sucedió en las ciudades-estado aztecas en México. _c._ 1200 dC.

Las ciudades-estado individuales en una cultura de ciudad-estado varían en tamaño geográfico y poblacional, pero como regla general ninguna de ellas es lo suficientemente fuerte como para someter a todas las demás y convertir a toda la región en un macroestado.

En una cultura de ciudad-estado hay guerra casi todo el tiempo entre al menos algunas de las ciudades-estado, pero al mismo tiempo existe una enorme interacción económica y cultural entre ellas.

En tiempos de paz, las ciudades-estado mantienen relaciones diplomáticas entre sí. Rara vez la cultura de una ciudad-estado consiste únicamente en ciudades-estado independientes: la mayoría de ellas son conjuntos de muchas ciudades-estado pequeñas y unas pocas ciudades-estado más grandes, y las más pequeñas a menudo se unen en ligas y federaciones dirigidas por una ciudad-estado más grande, o bien se convierten en dependencias de una gran ciudad-estado o del rey de un reino vecino.

Las culturas de las ciudades-estado a menudo se hunden porque surge en la región vecina un poderoso macroestado que somete a sí mismo toda la región de las ciudades-estado. Así llegaron a su fin las ciudades-estado sumerias _c._ 2350 a. C., siendo absorbidas desde el norte por el rey Sargón de Acad.

Las culturas de ciudades-estado suelen encontrarse en regiones vecinas y, en algunos casos, se puede hablar de grupos de culturas de ciudades-estado, _e.g_. en el Cercano Oriente, donde las ciudades-estado sumerias, babilónicas, asirias, anatolias, sirias, fenicias, neohititas, palestinas y filisteas, en el transcurso de 2.500 años, produjeron nueve culturas diferentes de ciudades-estado que limitaban entre sí.

Como ejemplo típico de cultura de ciudad-estado, se ofrece aquí una breve descripción de una cultura de África occidental. Al sur del lago Chad, en la parte más septentrional de Camerún, se encuentra el pueblo Kotoko, en una región de _c._ 8.000 km2. Su lengua pertenece a la familia Chad, son musulmanes y viven principalmente de la pesca. Desde la Edad Media hasta principios del siglo XX, la región estuvo dividida en catorce pequeños reinos, cada uno de los cuales constaba de una ciudad y su territorio circundante. Originalmente eran completamente independientes unos de otros, pero _c_.1600 se convirtieron en dependencias del Imperio Bornu. Y en el siglo XIX, doce de ellos se unieron en dos estados federales: los siete más al norte pasaron a formar parte de una federación gobernada por el príncipe de la ciudad Makari, mientras que los cinco más al sur formaron otra federación bajo el gobernador de la ciudad Logone Birni. El centro político, económico y religioso de cada ciudad-estado era una ciudad rodeada por una muralla protectora que, además de las viviendas, tenía también una mezquita, un palacio del sultán y un lugar de reunión con un _gudu_, una pequeña torre desde la que el sultán podía dirigirse al pueblo. Cada sultanato tenía un territorio de 100 a 1.000 km2. Una de las ciudades más grandes, Goulfeil, cubre _c._ 20 ha, y en 1873 la ciudad-estado tenía 8.000 habitantes, de los cuales aproximadamente la mitad vivía en la propia ciudad.9

La cultura de la ciudad-estado es un fenómeno histórico. Todavía hoy existen algunas ciudades-estado, por ejemplo San Marino y Andorra, y es común clasificar, por ejemplo, a Hamburgo y Singapur como ciudades-estado. Pero todos son casos aislados y ya no queda ninguna cultura de ciudad-estado en ningún lugar del mundo.

Hasta aquí el concepto de cultura de ciudad-estado. A continuación cambiaremos el enfoque del todo a la parte y estudiaremos los elementos individuales que componen una cultura de ciudad-estado, es decir, la ciudad-estado misma.10

Una ciudad-estado es un microestado tanto territorialmente como en población. Las ciudades-estado griegas antiguas más pequeñas tenían un territorio de aproximadamente 10 km2 y una población a veces inferior a 1.000 habitantes. La población de una de las ciudades-estado más pequeñas de Asia central era, alrededor del año 100 a.C., ¡como de 190 personas contadas! Es mucho más difícil establecer un límite superior. El territorio de una ciudad-estado es ante todo el interior de la ciudad, y una ciudad-estado que se expande más allá de su interior se convierte cada vez menos en una ciudad-estado. Si se considera tentativamente el interior de una ciudad como máximo a un día de marcha desde la ciudad hasta su frontera, un radio de 30 km dará un territorio de aproximadamente 3.000 km2 y una población de 300.000 habitantes cómo máximo. Atenas tenía un territorio de 2.500 km2 y, en el siglo IV a. C., una población de al menos 200.000 habitantes, de los cuales al menos 30.000 eran varones adultos ciudadanos de pleno derecho.

Una ciudad-estado suele estar formada por una sola ciudad y su interior. Si existen otros asentamientos nucleados dentro del territorio, en su mayoría tienen carácter de aldeas.

Es típico de las ciudades-estado que el nombre del estado sea el mismo que el nombre de la ciudad: por ejemplo, Atenas, Venecia, Andorra. En macroestados con muchas ciudades, el nombre del estado es el mismo que el nombre del país, e.g. Dinamarca, Estonia, Francia.

Una ciudad-estado a menudo se describe como una “sociedad de cara a cara”, es decir, una sociedad en la que todos tienen contacto personal con todos los demás (al menos con los ciudadanos varones adultos).

A diferencia de los estados-nación, que idealmente tienen una correspondencia entre identidad política y étnica, la población de una ciudad-estado siempre tendrá una identidad étnica diferente de la identidad política. La identidad étnica que los habitantes de la ciudad comparten con los habitantes de todas las demás ciudades-estado dentro de la cultura de la ciudad-estado, mientras que la identidad política y el sentimiento patriótico se dirigen hacia la ciudad-estado individual y tienen una fuerza que separa una ciudad-estado de otra.

En cuanto a la forma de asentamiento, una ciudad-estado se caracteriza por un nivel de urbanización mucho más alto que cualquier otra sociedad preindustrial. En las ciudades-estado más pequeñas, entre el 50 y el 90 por ciento de la población suele vivir dentro de las murallas de la ciudad, mientras que una población urbana de aproximadamente el 10 por ciento de la población total era típico de muchos macroestados, en la antigüedad y la Edad Media y en el período moderno temprano hasta _c._ 1750.

Las ciudades-estado muy pequeñas bien pueden haber tenido algo así como una economía de subsistencia, en la que cada hogar producía, en general, todo lo que necesitaba; pero las ciudades-estado medianas y grandes tenían división del trabajo, lo que conducía a una producción sustancial para un mercado local donde los ciudadanos compraban o intercambiaban la mayor parte de sus necesidades diarias, aparte de los artículos de lujo importados. En 1521 los españoles quedaron asombrados por el enorme comercio que se realizaba todos los días en los mercados de las ciudades-estado aztecas.

Una ciudad-estado se gobierna desde su centro y el gobierno no sólo está fuertemente centralizado sino también extremadamente institucionalizado. Muchas ciudades-estado tienen una forma republicana de gobierno (por ejemplo, las italianas y suizas en la Edad Media y más recientemente) y algunas incluso son democracias, como Atenas en la antigüedad.

Una ciudad-estado es un estado autónomo, pero no necesariamente independiente. Muchas ciudades-estado poseen lo que podríamos llamar soberanía “interna”, es decir, un gobierno que ejerce un Estado de derecho dentro de un territorio determinado sobre una población determinada, mientras que no tienen soberanía “externa”, es decir, independencia. Mileto en Asia Menor era una antigua ciudad-estado griega autónoma, pero desde _c._ 545 a. C. perteneció al Imperio persa y, posteriormente, a otras grandes potencias, y sólo fue una ciudad-estado independiente durante un breve periodo de tiempo, en el siglo V. Ahora bien, ¿en qué partes del mundo ha habido culturas de ciudades-estado?11 En el Cercano Oriente, a lo largo del llamado Creciente Fértil, hubo en la antigüedad un grupo de culturas de ciudades-estado: las sumeria, babilónica, asiria, anatolia, sirias, fenicias, neohititas, palestinas y filisteas. En el suroeste de Asia Menor estaban los licios, que crearon una cultura de ciudad-estado entre los siglos VI y IV a.C. En toda la esfera de la civilización griega antigua desde _c._ 750 a.C. al 500 d.C. existió una cultura de ciudad-estado, con unas 1.500 ciudades-estado. En Italia también existía en la antigüedad la cultura de ciudad-estado etrusca al norte de Roma y la latina que comprendía Roma y las ciudades del Lacio al sur de Roma.

En la Edad Media podemos encontrar culturas de ciudades-estado en el norte de Italia, el sur de Alemania y Suiza; y la República Holandesa fue fundada en 1579 como una especie de estado federal compuesto por cincuenta y siete ciudades. Tampoco hay que olvidar que los vikingos noruegos establecieron una cultura de ciudad-estado en Irlanda en el siglo X.

Más allá de Europa, no encontramos verdaderas culturas de ciudades-estado en América del Norte o del Sur, pero, por otro lado, en Mesoamérica sí hubo un conjunto de culturas de ciudades-estado. Los más importantes fueron los mayas en la península de Yucatán, las ciudades-estado mixtecas y zapotecas en la costa del Pacífico y los aztecas en el centro de México.

En África occidental había culturas de ciudades-estado en Nigeria, principalmente los Reinos Hausa al este del Níger, los reinos yoruba al oeste de ese río y las ciudades-estado dedicadas al comercio de esclavos en el delta del Níger; también las ciudades-estado de Fante a lo largo de la Costa Dorada y las ciudades-estado de Kotoko al sur del lago Chad. En la parte de África Oriental de habla suajili, en Kenia y Tanzania, existían las llamadas ciudades de piedra; y en un gran oasis en medio del Sahara se encontraban cinco pequeñas ciudades-estado habitadas desde 1012 por una tribu bereber llamada mozabita.

En el sudeste asiático, en la Edad Media, hubo una cultura de ciudad-estado en Tailandia y otra en Indonesia en el período _c._ 1400-1625. En Palembang, Sumatra, hay vestigios de una anterior, _c_.700–1100. China central estaba dividida en más de 200 ciudades-estado en el período de primavera y otoño, 771-481 a.C. Y en los oasis que rodeaban el borde del desierto de Taklamakan, en Asia Central, se encontraban veintiséis pequeñas ciudades-estado que sólo estuvieron integradas durante el Imperio chino _c._ 1780. Es más, en tiempos relativamente recientes el valle de Katmandú, en Nepal, estaba dividido entre tres o cuatro pequeñas ciudades-estado.

En conjunto, tenemos treinta y siete culturas de ciudades-estado identificables en la historia mundial. Nuestro equipo de académicos en el Centro Polis ha intentado por primera vez describirlas todas, pero debemos suponer que algunas han pasado desapercibidas o sólo serán reconocidas como culturas de ciudades-estado a la luz de esta investigación.

Este panorama revela que las culturas de ciudades-estado han ocurrido sólo en ciertas partes del mundo. Nunca hubo ninguno en Escandinavia ni en Inglaterra. En Francia y España se pueden encontrar ciudades-estado, pero sólo aisladas y por períodos cortos. En Alemania antes de 1806 había entre sesenta y cien, pero muchas de ellas estaban aisladas unas de otras y cercadas por ducados y obispados: sólo en el sur de Alemania había, a finales de la Edad Media y en el Renacimiento, una verdadera cultura de ciudad-estado como la de Suiza.

Así, en la mayor parte del mundo y durante la mayor parte de la historia mundial la gente no vivió en ciudades-estado sino en lo que, desde la Paz de Westfalia en 1648, se ha llamado “estados territoriales”. Y siguiendo ese concepto, se ha vuelto estándar ver las ciudades-estado y los estados territoriales como los dos polos de un par de opuestos. Pero como todas las ciudades-estado tenían un territorio bien definido, incluso si un pequeño, esa terminología ha llevado a la mente de las personas por un camino equivocado. Propongo en cambio que hagamos una distinción entre (pequeñas) ciudades-estado y (grandes) “países-estados”.12

¿Cuál es el punto de distinguir los conceptos de cultura de ciudad-estado y ciudad-estado? ¿Y de distinguir entre ciudades-estado y “países-estados”? ¿Hay alguna tendencia importante en la historia mundial que se destaque más claramente si contrastamos las culturas de los “países-estados” y las de las ciudades-estado? Creo que sí y avanzo tres consideraciones.

En primer lugar, a lo largo de la historia mundial hasta el siglo XVIII, todos los “países-estados” han sido monarquías. Muchas ciudades-estado eran también monarquías, pero la pequeña escala de las ciudades-estado significó que junto a las monarquías surgieran también oligarquías o democracias, es decir, estados donde el proceso de toma de decisiones políticas recaía en consejos y asambleas y donde las decisiones se tomaban sobre la base de votar y debatir. Es este patrón político el que prevalece en el mundo actual y tiene sus raíces en las culturas de las ciudades-estado. En las oligarquías era un consejo electo, en las democracias una asamblea popular, la que tomaba las decisiones. Ambos tipos de constitución tienen en común que se basan en decisiones mayoritarias después del debate en asambleas, en la selección de líderes y en cierto grado de rotación entre aquellos con derecho a participar en el proceso político. Antes del siglo XIX, ese sistema sólo podía aplicarse en los microestados, y los microestados eran ciudades-estado. La gran agitación en el proceso político se produjo en la segunda mitad del siglo XVIII con la Guerra de Independencia de Estados Unidos y la Revolución Francesa.13

Con la Revolución Francesa la democracia empezó a llegar a los macroestados. El ideólogo principal fue Jean-Jacques Rousseau: su concepto de democracia era una democracia de asamblea enteramente directa, que sólo se conocía en las ciudades-estado. Sus ideales eran la constitución de Roma _c._ 500 a. C. y la constitución oligárquica de su ciudad natal de Ginebra, que consideraba la democracia ideal. En ese punto de vista estaba equivocado; pero en el contexto actual eso no importa. Ginebra en el siglo XVIII era una ciudad-estado como la antigua Roma y, por lo tanto, toda la ideología política que surgió bajo la inspiración de Rousseau durante la Revolución Francesa, y bajo la cual vivimos hoy, tiene sus raíces en las culturas de las ciudades-estado.14

Después de la Guerra de Independencia de Estados Unidos, en 1787-1789, por primera vez en los tiempos modernos, los estadounidenses crearon una constitución estatal federal en la que los trece estados constituyentes y la federación compartían la soberanía entre ellos y, por lo tanto, no había ningún soberano en absoluto en el sentido clásico, porque, como sabemos, la soberanía es indivisible. Muchos en ese momento consideraban que tal constitución era imposible, pero sus defensores pudieron responder que había ejemplos históricos de una constitución de este tipo que funcionó extremadamente bien. Entre los ejemplos estaban la Liga Aquea y la Liga Aitolia, ambas fundadas en Grecia en 280/79 a. C., la confederación suiza de 1291 y la república federal holandesa fundada por el Tratado de Utrecht en 1579.15 Según Montesquieu (1748), el estado federal era típicamente una federación de pequeñas ciudades-estado,16 y los Padres Fundadores de la Revolución Americana eran conscientes de que estaban transfiriendo un sistema político histórico del nivel microestado al macroestado. Hoy en día, más de la mitad de la población del mundo vive en estados federales o en estados con aspectos federales. Así que, una vez más, nuestra civilización política se basa en ideas y estructuras que tienen sus raíces en las ciudades-estado y sólo después se adaptaron a los de "países-estados".17

En segundo lugar, con la creación de los estados federales se abrió una brecha en el concepto de estado. En Estados Unidos distinguieron entre los estados y la federación: Nueva York y Pensilvania eran estados, pero también lo era toda la federación. El “Estado” suele definirse como una institución que posee un monopolio legítimo de poder para defender un orden jurídico determinado dentro de un territorio específico y sobre una población específica. Según esa definición, un estado que es parte de una federación es, por supuesto, un estado; pero toda la federación es también un estado, y ya no podemos decir que un estado es un estado y que todos los estados son en principio iguales. Hemos creado, en esencia, un concepto jerárquico de Estado y, por lo tanto, hemos vuelto a la estructura (a menudo) jerárquica de las culturas de las ciudades-estado, en las que el autogobierno era un requisito necesario para ser una ciudad-estado, pero la independencia era un requisito no necesariamente requerido, y en el cual el estado federal era el modelo preferido para crear unidades políticas más grandes.18

En tercer lugar, una de las bases de la economía moderna es la urbanización. En los países industrializados, entre el 80 y el 90 por ciento de la población vive en ciudades,19 pero hace 250 años ocurría lo contrario: entre el 80 y el 90 por ciento de la población vivía en la tierra o en aldeas, y sólo entre el 10 y el 20 por ciento vivía en las ciudades.20 Una economía de subsistencia generalmente se encuentra en comunidades con baja urbanización, mientras que las economías de mercado van con comunidades con alta urbanización. Ahora bien, si hay algo que caracteriza a las culturas de las ciudades-estado en términos socioeconómicos es la urbanización y los mercados. Un buen ejemplo es la ciudad-estado de Assur en el norte de Mesopotamia y su centro comercial en Kanesh en Asia Menor, que en 1900 a. C. era el centro de todo el comercio de la región, en oro, plata, estaño y textiles.21 La investigación del Polis Centre sobre las treinta y siete culturas de ciudades-estado muestra que el economista británico John Hicks tenía razón en su afirmación (a menudo contradicha) de que la economía de mercado moderna surgió en las ciudades-estado.22

### Notas del Capítulo 1

1.  Este capítulo es una versión revisada y muy abreviada de mi Introducción y Conclusión en _30 CSC_: 11–34 y 597–623, y mi Introducción en _6 CSC_: 7–21. En la presente encuesta, las notas y referencias se han reducido al mínimo. La documentación completa se puede encontrar en los dos libros enumerados anteriormente.
    
2.  Mellaart (1967; 1975); Mieroop (1997) 26. Sobre la diferencia entre una ciudad y un pueblo, ver _infra_ 67–9 y 89–90.
    
3.  Este concepto heurístico de Estado se utiliza en antropología, sociología, arqueología e historia, y se aplica en todo el mundo a civilizaciones de todos los períodos. En la jurisprudencia y las ciencias políticas se encuentra comúnmente un concepto histórico mucho más estrecho de Estado: el Estado no es sólo un gobierno facultado para hacer cumplir un sistema legal dentro de un territorio sobre una población; también es un _abstracción_, es decir, un poder público continuo por encima tanto del gobernante como de los gobernados, y una comunidad debe tener un _soberano_ gobierno y debe estar en posesión de _plena soberanía exterior_ para ser un estado. De esta forma surgió en Europa el concepto de Estado. Se remonta a mediados del siglo XVII y floreció en los siglos XIX y XX. Sólo podrá utilizarse en todo el mundo después de mediados del siglo XX. Sobre la diferencia entre estos dos conceptos de Estado, véase 30 CSC: 12-14. Sobre los diversos elementos del concepto de Estado, véase Hansen (1998) 35-51.
    
4.  Southall (1998), 16, describe a Çatal Höyük como ciudad-estado, lo cual me parece poco probable (_30 CSC_: 15, 605), véase Mithen (2003) 95.
    
5.  Arnold (1997) 211–30.
    
6.  Forde (1964); _6 CSC_: 26–7.
    
7.  Olsen (1989).
    
8.  _30 CSC_: 16-17; _6 CSC_: 12-16.
    
9.  _30 CSC_: 531–2.
    
10.  _Ibídem_. 17-19.
    
11.  Ver la encuesta _infra_ 17–23.
    
12.  _30 CSC_: 16. El término “países-estados” fue, de hecho, sugerido por Henry Sidgwick _c._ 1900, seguido de Finer (1997) 6-7, y ambos rechazaron el término “estado territorial” por considerarlo inapropiado en este contexto.
    
13.  _30 CSC_: 611–12.
    
14.  J. Miller (1984); _30 CSC_: 612.
    
15.  _30 CSC_: 612–13.
    
16.  Montesquieu, _Del espíritu de las Leyes_, Libro 9, caps. 1–3.
    
17.  Eleazar (1994), pág. xv; _30 CSC_: 612–13.
    
18.  Hansen (1998) 46–7, 121.
    
19.  Es imposible ser preciso, porque cada estado tiene su propia definición de lo que es un pueblo o ciudad. En Dinamarca, un asentamiento con más de 200 habitantes cuenta como pueblo/ciudad (_by_), mientras que en la India el requisito es de 5.000 habitantes.
    
20.  Bairoch (1988) 137. La relación 90:10 se basa en el supuesto de que un centro urbano debe tener 5.000 habitantes para contar como ciudad. 80: 20 es mi estimación aproximada de la proporción si aceptamos 1.000 como población mínima.
    
21.  M. Trolle Larsen (1976).
    
22.  Hicks (1969) 42–3; _30 CSC_: 614–15.
